export const provincias = [
  {
    id: 'bocas-del-toro',
    nombre: 'Bocas del Toro',
    banner: {
      tipo: 'video',
      src: '/videos/bocasDelToro/bocasBanner.av1.mp4',
      alt: 'Costa caribeña de la provincia de Bocas del Toro',
    },
    descripcionCorta:
      'Un rincón caribeño donde la naturaleza se siente en cada ola. Descubre islas de aguas cristalinas, playas de arena blanca y una cultura alegre que combina tradición indígena y esencia afrocaribeña en un ambiente único.',
    imagenProvincia: {
      src: '',
      alt: 'Paisaje representativo de Bocas del Toro',
    },
    ubicacionProvincia: {
      src: 'https://www.google.com/maps?q=Bocas%20del%20Toro%20Province%2C%20Panama&output=embed',
    },
    actividades: [
      'Surf',
      'Buceo',
      'Snorkel',
      'Senderismo',
      'Kayak',
      'Ciclismo',
      'Recorrido histórico',
      'Caminata',
      'Gastronomía',
      'Turismo cultural',
      'Fotografía',
      'Paseos en lancha',
      'Avistamiento de aves',
      'Artesanías',
      'Avistamiento de delfines',
      'Snorkel en arrecifes',
      'Kayak entre manglares',
      'Expedición fotográfica',
      'Caminata costera',
      'Observación de medusas',
      'Navegación al atardecer',
      'Intercambio comunitario',
      'Estrellas de mar',
      'Natación',
      'Vida marina',
      'Exploración',
      'Avistamiento de tortugas',
      'Pícnic',
      'Ranas rojas',
      'Exploración de cuevas',
      'Cultura',
      'Descanso',
      'Atardeceres',
      'Bioluminiscencia',
      'Tour de cacao',
    ],
    directSiteIds: [
      'isla-colon',
      'isla-bastimentos',
      'cayo-zapatilla',
      'isla-carenero',
      'bahia-de-los-delfines',
      'cayo-coral',
      'almirante',
    ],
    displayMode: 'sites-only',
  },
]
